project:
  type: website
  output-dir: docs

website:
  title: "Fortificación de alimentos a gran escala"
  description: "sitio web para asistencia técica de fortificación de alimentos"
  favicon: favicon.png
  reader-mode: true
  search:
    location: navbar
    type: overlay
  navbar:
    pinned: true
    logo: logo.png
    left:
      - href: index.qmd
        text: "🏠 Home"
      - href: about.qmd 
        text: "📄 About" 
  sidebar:
    contents: auto

               

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    include-after-body: _footer.html  # <-- Esta es la magia de forti

editor: visual

